services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    networks:
      internal:
        ipv4_address: 172.30.2.20
    ports:
      - "8087:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=rikdecan
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123 #10/10 secure password
      - DOCKER_INFLUXDB_INIT_ORG=pointcare
      - DOCKER_INFLUXDB_INIT_BUCKET=sensors
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=700d5d63-ef50-47b5-a90c-cdeff2f823b7 #generated GUID token
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2

  ingestion-service:
    build:
      context: ./ingestion-service
      dockerfile: Dockerfile
    container_name: ingestion-service
    networks:
      internal:
        ipv4_address: 172.30.2.30
    depends_on:
      - influxdb
    restart: unless-stopped

  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    container_name: mcp-server
    networks:
      internal:
        ipv4_address: 172.30.2.10
    environment:
      - INFLUXDB_URL=http://172.30.2.20:8086
      - INFLUXDB_TOKEN=700d5d63-ef50-47b5-a90c-cdeff2f823b7
      - INFLUXDB_ORG=pointcare
      - INFLUXDB_BUCKET=sensors
    depends_on:
      - influxdb
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
      external:
        ipv4_address: 172.30.1.10
      internal:
        ipv4_address: 172.30.2.100
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mcp-server
    restart: unless-stopped

  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    container_name: llm
    networks:
      external:
        ipv4_address: 172.30.1.20
    ports:
      - "8080:8080"
    volumes:
      - ./llm/models:/models:ro
    depends_on:
      - nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  external:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/24
          gateway: 172.30.1.1
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.2.0/24
          gateway: 172.30.2.1

volumes:
  influxdb-data:
  influxdb-config: